language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tyra777/react-docker-cloud -f Dockerfile.dev .


script:
  - docker run -e CI=true tyra777/react-docker-cloud npm run test